### ISSUE TITLE
Form Helpers

### ISSUE THREAD

**Issue by nixpulvis** [stephencelis/acts_as_singleton#10]
Trying to make a form with a singleton model using `form_for` doesn't really work. It'd be nice if it did work.

**Comment by ka8725** [comment]
How do you try it within `form_for`?

**Comment by nixpulvis** [comment]
I gave it another whirl, I'm not actually sure what I thought the problem was when I opened this bug. I'll lay off the crack I guess. Sorry for wasting brain cycles.
