### ISSUE TITLE
Possible thread-safety issue

### ISSUE THREAD

**Issue by ghost** [stephencelis/acts_as_singleton#11]
the `instance` method should be

``` ruby
def instance
  self.transaction { first || create }
end
```

thereby preventing more than one record from being `create`'ed

**Comment by ghost** [comment]
would you accept a patch for this?

**Comment by stephencelis** [comment]
Hm, transactions are useful when you're making multiple insertions and don't want any one of them inserted unless all are inserted. I don't think this patch would really do anything to prevent a race condition from inserting multiple rows (please correct me if I'm wrong).

If you're worried about production race conditions, insert the row (create the instance) before you expose any incoming requests to a new acts_as_singleton model.
