### ISSUE TITLE
acts_as_single fails when polymorphic association uses validates_associated

### ISSUE THREAD

**Issue by jlsync** [stephencelis/acts_as_singleton#2]
Given

```
 class God
   acts_as_singleton
  has_many :children, :as => :parent
 end

 class Child
   belongs_to :parent, :polymorphic => true
   validates_associated :parent
 end
```

Child create seems to fail because the validation is calling 'find' on God which is now a private acts_as_singlton method.

**Comment by stephencelis** [comment]
Allow 'find' calls from ActiveRecord [closed by 8011cb60bc6c07c91a485eb990be4b44f8e4a660].
