### ISSUE TITLE
rails 3 compatibility

### ISSUE THREAD

**Issue by troessner** [stephencelis/acts_as_singleton#4]
The code below is running perfectly well with rails 2.3.5 but not with rails 3.0.0.4beta:

class FeaturedMember < ActiveRecord::Base
  acts_as_singleton
  belongs_to :user
end

( $ )  rails c
Loading development environment (Rails 3.0.0.beta4)
irb(main):001:0> FeaturedMember.instance
NoMethodError: private method `find_by_sql' called for #<Class:0xb5bde13c>
        from /usr/lib/ruby/gems/1.8/gems/activerecord-3.0.0.beta4/lib/active_record/base.rb:1016:in`method_missing' from /usr/lib/ruby/gems/1.8/gems/activerecord-3.0.0.beta4/lib/active_record/relation.rb:64:in `to_a' from /usr/lib/ruby/gems/1.8/gems/activerecord-3.0.0.beta4/lib/active_record/relation/finder_methods.rb:324:in`find_first' from /usr/lib/ruby/gems/1.8/gems/activerecord-3.0.0.beta4/lib/active_record/relation/finder_methods.rb:117:in `first' from /usr/lib/ruby/gems/1.8/gems/activerecord-3.0.0.beta4/lib/active_record/base.rb:403:in`**send**'  from /usr/lib/ruby/gems/1.8/gems/activerecord-3.0.0.beta4/lib/active_record/base.rb:403:in `first' from /usr/lib/ruby/gems/1.8/gems/acts_as_singleton-0.0.4/lib/acts_as_singleton.rb:43:in`instance' from (irb):1
irb(main):002:0>

**Comment by troessner** [comment]
Apparently i missed this: http://github.com/stephencelis/acts_as_singleton/issues/closed#issue/3
Added github as source in my Gemfile and everything is working as expected.

**Comment by stephencelis** [comment]
I've updated the official gem on rubygems! Thanks.
