### ISSUE TITLE
This gem doesn't play fine with rails 3.2

### ISSUE THREAD

**Issue by pedrorolo** [stephencelis/acts_as_singleton#7]
When invoking ::instance

ArgumentError: wrong number of arguments (2 for 1)
    from /.rvm/gems/ruby-1.8.7-p357/gems/activerecord-3.2.1/lib/active_record/relation.rb:170:in `find_by_sql'
    from /.rvm/gems/ruby-1.8.7-p357/gems/activerecord-3.2.1/lib/active_record/relation.rb:170:in`exec_queries'
    from /.rvm/gems/ruby-1.8.7-p357/gems/activerecord-3.2.1/lib/active_record/relation.rb:159:in `to_a'
    from /.rvm/gems/ruby-1.8.7-p357/gems/activerecord-3.2.1/lib/active_record/explain.rb:40:in`logging_query_plan'
    from /.rvm/gems/ruby-1.8.7-p357/gems/activerecord-3.2.1/lib/active_record/relation.rb:158:in `to_a'
    from /.rvm/gems/ruby-1.8.7-p357/gems/activerecord-3.2.1/lib/active_record/relation/finder_methods.rb:377:in`find_first'
    from /.rvm/gems/ruby-1.8.7-p357/gems/activerecord-3.2.1/lib/active_record/relation/finder_methods.rb:122:in `first'
    from /.rvm/gems/ruby-1.8.7-p357/gems/activerecord-3.2.1/lib/active_record/querying.rb:5:in`**send**'
    from /.rvm/gems/ruby-1.8.7-p357/gems/activerecord-3.2.1/lib/active_record/querying.rb:5:in `first'
    from /.rvm/gems/ruby-1.8.7-p357/gems/acts_as_singleton-0.0.5/lib/acts_as_singleton.rb:43:in`instance'

**Comment by blueblank** [comment]
I'm having issues with this too, moving a project to Rails 3.2.0 when calling .instance

ArgumentError: wrong number of arguments (2 for 1)
from /home/x/.rvm/gems/ruby-1.9.3-p0/gems/acts_as_singleton-0.0.5/lib/acts_as_singleton.rb:58:in `find_by_sql'

**Comment by pedrorolo** [comment]
Hey! Apparently this fork already works with rails 3.2 : https://github.com/iquest/acts_as_singleton .
It would be nice if you could pull from it an publish the gem.

**Comment by stephencelis** [comment]
Fixed with #8.
